---
- name: Install jmespath for JSON parsing
  local_action:
    module: pip
    name: jmespath
    state: latest

- name: Fetch latest release info
  uri:
    url: "https://api.github.com/repos/{{ owner }}/{{ repo }}/releases/{% if tag is defined %}tags/{{ tag }}{% else %}latest{% endif %}"
  register: gh_rel

# Lovely JMESPath expression to extract asset URL for a certain prefix/suffix.
# Oh yes, gotta love that beautiful and trivial escaping <3
- set_fact:
    noobuntu_github_release_url: "{{ gh_rel.json | json_query('assets[? starts_with(name, `\"' + prefix + '\"`) && ends_with(name, `\"' + suffix + '\"`)].browser_download_url') | first }}"
